atomic:
  CV.cv_click:
    title: 点击图像
    comment: 鼠标(@{btn_type})(@{btn_model})图像(@{input_data})(@{click_position})
    icon: click-image
    helpManual: 在当前(激活)窗口检索目标图片，并在窗口界面中点击该图片。
    inputList:
    - key: input_data
      title: 目标图像
      tip: 支持从图形库中选择或拾取图像获取图像元素
    - key: btn_type
      title: 鼠标按键
      tip: ''
    - key: btn_model
      title: 点击方式
      tip: ''
    - key: click_position
      title: 点击位置
      tip: 选择鼠标点击位置
    - key: specified_position
      title: 指定位置
      tip: ''
    - key: horizontal_move
      title: 横向平移
      tip: ''
    - key: vertical_move
      title: 纵向平移
      tip: ''
    - key: match_similarity
      title: 匹配相似度
      tip: 查找目标图像与当前页面的相似度阈值(最高匹配精确度为99%)，精准匹配表示当前界面存在于截取的目标图像完全一致的时候才能匹配成功
    - key: move_type
      title: 鼠标移动方式
      tip: ''
    - key: move_speed
      title: 鼠标移动速度
      tip: ''
    - key: wait_time
      title: 等待图像出现时间(秒)
      tip: 超过该时间停止等待，默认为10秒
    outputList: []
  CV.hover_image:
    title: 鼠标悬浮在图像上
    comment: 鼠标悬浮在图像(@{input_data})的(@{click_position})
    icon: mouse-hover-image
    helpManual: 在当前(激活)窗口检索图像，并将鼠标移动到该图像的指定位置上。
    inputList:
    - key: input_data
      title: 目标图像
      tip: 支持从图形库中选择或拾取图像获取图像元素
    - key: click_position
      title: 悬浮位置
      tip: ''
    - key: specified_position
      title: 指定位置
      tip: 按照九宫格切割图像，支持选择九宫格任意一个区域，选择区域则悬浮在目标图像对应区域的中心点位置
    - key: horizontal_move
      title: 横向平移
      tip: ''
    - key: vertical_move
      title: 纵向平移
      tip: ''
    - key: match_similarity
      title: 匹配相似度
      tip: 查找目标图像与当前页面的相似度阈值(最高匹配精确度为99%)，精准匹配表示当前界面存在于截取的目标图像完全一致的时候才能匹配成功
    - key: move_type
      title: 鼠标移动方式
      tip: ''
    - key: move_speed
      title: 鼠标移动速度
      tip: ''
    - key: wait_time
      title: 等待图像出现时间(秒)
      tip: 超过该时间停止等待，默认为10秒
    outputList: []
  CV.is_image_exist:
    title: IF 图像存在
    comment: 判断图像(@{input_data})在当前界面(@{exist_type})
    icon: if-image-exists
    helpManual: 在当前(激活)窗口检索图像，判断是否存在。
    inputList:
    - key: input_data
      title: 目标图像
      tip: 支持从图形库中选择或拾取图像获取图像元素
    - key: exist_type
      title: 判断类型
      tip: 判断图像存在或不存在，分别执行对应代码块内容
    - key: match_similarity
      title: 匹配相似度
      tip: 查找目标图像与当前页面的相似度阈值(最高匹配精确度为99%)，精准匹配表示当前界面存在于截取的目标图像完全一致的时候才能匹配成功
    - key: wait_time
      title: 等待图像时间(秒)
      tip: 超过该时间停止等待，默认为10秒
    outputList: []
  CV.wait_image:
    title: 等待图像
    comment: 等待图像(@{input_data})(@{wait_type})
    icon: wait-image
    helpManual: 等待目标图像出现或消失，再继续执行流程。
    inputList:
    - key: input_data
      title: 目标图像
      tip: 支持从图形库中选择或拾取图像获取图像元素
    - key: wait_type
      title: 等待类型
      tip: 等待图像出现或消失
    - key: wait_time
      title: 等待时间(秒)
      tip: 超过该时间停止等待，默认为10秒
    - key: match_similarity
      title: 匹配相似度
      tip: 查找目标图像与当前页面的相似度阈值(最高匹配精确度为99%)，精准匹配表示当前界面存在于截取的目标图像完全一致的时候才能匹配成功
    outputList:
    - key: image_wait_result
      title: 等待结果
      tip: 目标图像是否出现/消失，在等待时间内出现/消失为true，反之为false
  CV.image_input:
    title: 图像输入框输入
    comment: 拾取图像输入框(@{input_data})以(@{input_type})输入(@{input_content})
    icon: image-input-box
    helpManual: 点击目标输入框的图像，并输入内容
    inputList:
    - key: input_data
      title: 目标图像
      tip: 支持从图形库中选择或拾取图像获取图像元素
    - key: input_type
      title: 输入方式
      tip: ''
    - key: input_content
      title: 输入内容
      tip: ''
    - key: simulate_flag
      title: 模拟人工输入
      tip: ''
    - key: interval
      title: 输入间隔
      tip: ''
    - key: match_similarity
      title: 匹配相似度
      tip: ''
    - key: wait_time
      title: 等待图像出现时间(秒)
      tip: 超过该时间停止等待，默认为10秒
    outputList: []
options:
  BtnType:
  - value: left
    label: 左键
  - value: middle
    label: 中键
  - value: right
    label: 右键
  BtnModel:
  - value: click
    label: 单击
  - value: double_click
    label: 双击
  PositionType:
  - value: center
    label: 中心点
  - value: random
    label: 随机位置
  - value: specific
    label: 指定位置
  MoveType:
  - value: linear
    label: 匀速直线
  - value: simulation
    label: 模拟人工
  - value: teleportation
    label: 瞬时移动
  Speed:
  - value: slow
    label: 慢速
  - value: normal
    label: 正常
  - value: fast
    label: 快速
  ExistType:
  - value: exist
    label: 存在
  - value: not_exist
    label: 不存在
  WaitType:
  - value: appear
    label: 图像出现
  - value: disappear
    label: 图像消失
  InputType:
  - value: text
    label: 字符输入
  - value: clip
    label: 剪切板输入
  Simulate_flag:
  - value: 'yes'
    label: 是
  - value: 'no'
    label: 否
