atomic:
  Software.open:
    title: 打开程序
    comment: 打开应用程序路径(@{app_abs_path})，并设置运行参数为(@{app_args})，将结果输出为(@{software_open})
    icon: open-program
    helpManual: ''
    inputList:
    - key: app_abs_path
      title: 应用程序路径
      tip: 输入需要打开的应用程序文件路径
    - key: app_args
      title: 运行参数
      tip: 用于部分程序依赖的运行参数，例：程序环境变量
    outputList:
    - key: software_open
      title: 应用程序路径
      tip: 输出该被打开的应用程序路径
  Software.close:
    title: 关闭程序
    comment: 关闭应用程序路径为(@{app_abs_path})的程序
    icon: close-program
    helpManual: ''
    inputList:
    - key: app_abs_path
      title: 应用程序路径
      tip: 需要被关闭的应用程序路径
    outputList: []
  Software.cmd:
    title: Cmd命令
    comment: 通过配置cmd字符串(@{cmd})，执行cmd命令，执行结果保存至(@{exec_cmd})
    icon: cmd-command
    helpManual: ''
    inputList:
    - key: cmd
      title: cmd字符串
      tip: 输入cmd字符串
    outputList:
    - key: exec_cmd
      title: 执行结果
      tip: 输出自定义cmd命令运行后返回的对象结果
