atomic:
  Script.module:
    title: 运行Python模块
    comment: 运行Python模块(@{content:Python模块})
    icon: run-python-module
    helpManual: ''
    inputList:
    - key: content
      title: 选择Python模块
      tip: ''
    outputList:
    - key: program_script
      title: 执行结果
      tip: ''
options: {}
