types:
  ExcelObj:
    desc: Excel对象
    funcList:
      - key: ExcelObj.get_full_name
        funcDesc: 文件所在位置
      - key: ExcelObj.get_row_count
        funcDesc: 可用行的总行数
      - key: ExcelObj.get_first_free_row
        funcDesc: 第一个可用行