[project]
name = "astronverse-baseline"
version = "1.0.0"
description = "astronverse-baseline."
requires-python = ">=3.13"

dependencies = [
    "loguru",
    "toml",
]

[tool.hatch.build.targets.wheel]
packages = ["src/astronverse"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"