types:
  Any:
    desc: "任意类型"
  Float:
    desc: "数值"
  Int:
    desc: "整数"
  Bool:
    desc: "布尔值"
  Str:
    desc: "字符串"
  List:
    desc: "列表"
  Dict:
    desc: "字典"
  Date:
    desc: "日期时间"
  PATH:
    desc: "文件路径"
  URL:
    desc: "地址"
  Pick:
    desc: "元素"
  WebPick:
    desc: "网页元素"
  WinPick:
    desc: "Win元素"
  DialogResult:
    desc: "对话框输出结果"
options:
  bool:
    - value: "True"
      label: "是"
    - value: "False"
      label: "否"
  Bool:
    - value: "True"
      label: "是"
    - value: "False"
      label: "否"