atomic:
  Dialog.message_box:
    title: 消息提示框
    comment: ''
    icon: message-dialog
    helpManual: 打开消息提示对话框，可设定消息提示的内容和标题。
    inputList:
    - key: box_title
      title: 对话框标题
      tip: 用户自定义的对话框上方的显示标题，限制标题内容字符数量为50个字符。不输入则默认标题为“消息提示框”
    - key: message_type
      title: 消息类型
      tip: 可选消息类型
    - key: message_content
      title: 消息内容
      tip: 用户自定义的对话框内的显示内容，限制内容字符数量为120个字符
    - key: button_type
      title: 展示按钮
      tip: 消息框可展示给用户进行选择的按钮，只允许切换，不允许空选状态
    - key: auto_check
      title: 无操作自动关闭对话框
      tip: ''
    - key: wait_time
      title: 无操作超时等待（秒）
      tip: 设置超时等待时间，未识别到用户鼠标移动行为超过该时间则选中默认按钮，默认为60秒
    - key: default_button_c
      title: 超时默认选中按钮
      tip: ''
    - key: default_button_cn
      title: 超时默认选中按钮
      tip: ''
    - key: default_button_y
      title: 超时默认选中按钮
      tip: ''
    - key: default_button_yn
      title: 超时默认选中按钮
      tip: ''
    - key: preview_button
      title: 预览
      tip: ''
    outputList:
    - key: result_button
      title: 保存用户选择的按钮至
      tip: ''
  Dialog.input_box:
    title: 输入对话框
    comment: ''
    icon: input-dialog
    helpManual: 打开输入对话框，需用户进行信息输入并确定提交，返回用户在对话框中输入的内容。
    inputList:
    - key: box_title
      title: 对话框标题
      tip: 限制标题内容字符数量为50个字符，不输入则默认标题为“输入对话框”
    - key: input_type
      title: 输入框类型
      tip: ''
    - key: input_title
      title: 输入框标题
      tip: ''
    - key: default_input_text
      title: 输入框内容默认值
      tip: 填写则在对话框中展示默认文本作为文本提示符，限制内容字符数量为120个字符
    - key: default_input_pwd
      title: 输入框内容默认值
      tip: 填写则在对话框中展示默认密码，密码长度在4-16位之间
    - key: preview_button
      title: 预览
      tip: ''
    outputList:
    - key: input_content
      title: 保存用户输入内容至
      tip: ''
  Dialog.select_box:
    title: 选择对话框
    comment: ''
    icon: select-dialog
    helpManual: 打开选择对话框，保存用户从选择列表中选择的一个或多个选项
    inputList:
    - key: box_title
      title: 对话框标题
      tip: ''
    - key: select_type
      title: 选择模式
      tip: ''
    - key: options
      title: 选项
      tip: ''
    - key: options_title
      title: 选择框标题
      tip: ''
    - key: preview_button
      title: 预览
      tip: ''
    outputList:
    - key: select_result
      title: 保存选择结果至
      tip: ''
  Dialog.select_time_box:
    title: 日期时间选择框
    comment: ''
    icon: datetime-picker
    helpManual: 打开日期时间选择框，保存用户选择的日期或时间
    inputList:
    - key: box_title
      title: 对话框标题
      tip: ''
    - key: time_type
      title: 时间类型
      tip: ''
    - key: time_format
      title: 时间格式
      tip: ''
    - key: default_time
      title: 默认时间
      tip: ''
    - key: default_time_range
      title: 默认时间
      tip: ''
    - key: input_title
      title: 输入框标题
      tip: ''
    - key: preview_button
      title: 预览
      tip: ''
    outputList:
    - key: select_time
      title: 保存时间选择结果至
      tip: ''
  Dialog.select_file_box:
    title: 文件选择对话框
    comment: ''
    icon: file-select-dialog
    helpManual: 打开系统选择文件对话框，保存用户选择的对应的文件/文件夹路径
    inputList:
    - key: box_title_file
      title: 对话框标题
      tip: ''
    - key: box_title_folder
      title: 对话框标题
      tip: ''
    - key: open_type
      title: 打开类型
      tip: ''
    - key: file_type
      title: 文件类型
      tip: ''
    - key: multiple_choice
      title: 是否允许多选
      tip: ''
    - key: select_title
      title: 选择框标题
      tip: ''
    - key: default_path
      title: 默认文件夹
      tip: 当配置了该参数，则在打开文件选择框时默认解析在该文件夹路径进行下一步选择
    - key: preview_button
      title: 预览
      tip: ''
    outputList:
    - key: select_file
      title: 保存文件选择结果至
      tip: 保存用户的文件选择结果，如果用户点击取消按钮则返回为空值
  Dialog.custom_box:
    title: 自定义对话框
    comment: ''
    icon: custom-dialog
    helpManual: ''
    inputList:
    - key: box_title
      title: 对话框标题
      tip: ''
    - key: design_interface
      title: 设计对话框界面
      tip: 点击按钮则进入对话框设计弹窗界面
      value: ''
    - key: auto_check
      title: 无操作自动关闭对话框
      tip: ''
    - key: wait_time
      title: 无操作超时等待（秒）
      tip: ''
    - key: default_button
      title: 超时默认选中按钮
      tip: ''
    outputList:
    - key: dialog_result
      title: 自定义对话框结果
      tip: 存储所有表单控件的输出结果以及点击的按钮结果
options:
  MessageType:
  - value: message
    label: 信息
  - value: warning
    label: 警告
  - value: question
    label: 问题
  - value: error
    label: 错误
  ButtonType:
  - value: confirm
    label: 确认
  - value: confirm_cancel
    label: 确认-取消
  - value: yes_no
    label: 是-否
  - value: yes_no_cancel
    label: 是-否-取消
  Bool:
  - value: true
    label: 是
  - value: false
    label: 否
  DefaultButtonC:
  - value: confirm
    label: 确认
  DefaultButtonCN:
  - value: confirm
    label: 确认
  - value: cancel
    label: 取消
  DefaultButtonY:
  - value: 'yes'
    label: 是
  - value: 'no'
    label: 否
  DefaultButtonYN:
  - value: 'yes'
    label: 是
  - value: 'no'
    label: 否
  - value: cancel
    label: 取消
  InputType:
  - value: text
    label: 文本框
  - value: password
    label: 密码框
  SelectType:
  - value: single
    label: 单选
  - value: multi
    label: 多选
  TimeType:
  - value: time
    label: 时间
  - value: time_range
    label: 时间段
  TimeFormat:
  - value: YYYY-MM-DD
    label: 年-月-日
  - value: YYYY-MM-DD HH:mm
    label: 年-月-日 时:分
  - value: YYYY-MM-DD HH:mm:ss
    label: 年-月-日 时:分:秒
  - value: YYYY/MM/DD
    label: 年/月/日
  - value: YYYY/MM/DD HH:mm
    label: 年/月/日 时:分
  - value: YYYY/MM/DD HH:mm:ss
    label: 年/月/日 时:分:秒
  OpenType:
  - value: file
    label: 文件
  - value: folder
    label: 文件夹
  FileType:
  - value: '*'
    label: 所有文件
  - value: .xls,.xlsx
    label: Excel文件
  - value: .doc,.docx
    label: Word文件
  - value: .txt
    label: 文本文件
  - value: .png,.jpg,.jpeg,.bmp,.gif
    label: 图像文件
  - value: .ppt,.pptx
    label: PPT文件
  - value: .zip,.rar
    label: 压缩文件
