atomic:
  WinEle.click_element:
    title: 点击元素（桌面）
    comment: '@{click_type} 拾取到的元素 @{pick} ，最长等待 @{wait_time} 秒直到此元素出现'
    icon: click-element-win
    helpManual: ''
    inputList:
    - key: pick
      title: 元素拾取
      tip: ''
    - key: click_button
      title: 点击按钮
      tip: ''
    - key: click_type
      title: 点击类型
      tip: ''
    - key: wait_time
      title: 等待元素出现时间
      tip: ''
    - key: horizontals_offset
      title: 横向偏移量
      tip: ''
    - key: verticals_offset
      title: 纵向偏移量
      tip: ''
    - key: keyboard_input
      title: 键盘辅助输入
      tip: 点击时同时按下键盘上的某些键
    outputList: []
  WinEle.screenshot_element:
    title: 元素截图（桌面）
    comment: 截图拾取到的元素 @{pick} ，并保存至文件夹 @{file_path}
    icon: element-screenshot-win
    helpManual: ''
    inputList:
    - key: pick
      title: 元素拾取
      tip: ''
    - key: file_path
      title: 文件保存路径
      tip: ''
    - key: file_name
      title: 文件名
      tip: ''
    - key: exist_type
      title: 文件同名时处理方式
      tip: ''
    outputList: []
  WinEle.hover_element:
    title: 鼠标悬停元素（桌面）
    comment: 鼠标悬停拾取到的元素 @{pick} ，并设置等待时间 @{wait_time} 秒
    icon: mouse-hover-element-win
    helpManual: ''
    inputList:
    - key: pick
      title: 元素拾取
      tip: ''
    - key: wait_time
      title: 等待元素出现时间
      tip: ''
    outputList: []
  WinEle.input_text_element:
    title: 填写输入框（桌面）
    comment: 填写输入框 @{pick} ，并设置输入类型为 @{input_type} ，输入内容为 @{text}
    icon: fill-input-win
    helpManual: ''
    inputList:
    - key: pick
      title: 元素拾取
      tip: ''
    - key: input_type
      title: 输入类型
      tip: ''
    - key: text
      title: 输入内容
      tip: ''
    - key: clear_first
      title: 是否清空输入框内容
      tip: ''
    - key: wait_time
      title: 等待元素出现时间
      tip: ''
    outputList: []
  WinEle.get_element_text:
    title: 获取元素文本（桌面）
    comment: 从元素 @{pick} 提取文本并保存到 @{ele_text}
    icon: get-element-text-win
    helpManual: ''
    inputList:
    - key: pick
      title: 元素拾取
      tip: ''
    - key: wait_time
      title: 等待元素出现时间
      tip: ''
    outputList:
    - key: ele_text
      title: 元素文本
      tip: ''
  WinEle.similar:
    title: 获取相似元素列表（桌面）
    comment: 获取拾取到的元素 @{pick} 相似的元素，并将相似元素数组输出至 @{get_similar_ele}
    icon: get-similar-elements-win
    helpManual: ''
    inputList:
    - key: pick
      title: 相识元素拾取
      tip: 在桌面上拾取不同位置的两个相似元素
    - key: wait_time
      title: 等待元素出现时间（秒）
      tip: 超过该时间停止等待
    outputList:
    - key: get_similar_ele
      title: 元素信息
      tip: ''
options:
  MouseClickButton:
  - value: left
    label: 左键
  - value: right
    label: 右键
  - value: middle
    label: 中键
  MouseClickType:
  - value: click
    label: 单击
  - value: double_click
    label: 双击
  MouseClickKeyboard:
  - value: none
    label: 不使用
  - value: alt
    label: Alt键
  - value: ctrl
    label: Ctrl键
  - value: shift
    label: Shift键
  - value: win
    label: Win键
  FileExistenceType:
  - value: overwrite
    label: 覆盖原有文件
  - value: rename
    label: 创建文件副本
  - value: cancel
    label: 取消保存操作
  ElementInputType:
  - value: keyboard
    label: 键盘输入
  - value: clipboard
    label: 剪贴板输入
  Bool:
  - value: true
    label: 是
  - value: false
    label: 否
