atomic:
  VerifyCode.picture_code:
    title: 通用数英验证码
    comment: 识别浏览器中的验证码 @{picture_pick} ，返回识别结果 @{code_result}
    icon: captcha-text
    helpManual: ''
    inputList:
    - key: browser_obj
      title: 浏览器对象
      tip: ''
    - key: picture_pick
      title: 拾取验证码对象
      tip: ''
    - key: code_type
      title: 验证码类型
      tip: ''
    - key: input_flag
      title: 是否填写输入框
      tip: ''
    - key: input_box
      title: 输入框对象
      tip: ''
    outputList:
    - key: code_result
      title: 识别结果
      tip: ''
  VerifyCode.slider_code:
    title: 通用滑块验证码
    comment: 在背景图为 @{picture_pick} 的滑块验证码上，拖动滑块 @{slider_pick} 至指定位置，拖动距离为 @{drag_distance}
    icon: captcha-slider
    helpManual: ''
    inputList:
    - key: browser_obj
      title: 浏览器对象
      tip: ''
    - key: picture_pick
      title: 背景图片对象
      tip: ''
    - key: slider_pick
      title: 拾取滑块对象
      tip: ''
    - key: unmatched_flag
      title: 是否为变速验证码
      tip: ''
    - key: move_pic_pick
      title: 拾取滑动图片对象
      tip: ''
    - key: mini_step
      title: 微调步长（px）
      tip: ''
    outputList:
    - key: drag_distance
      title: 移动距离
      tip: ''
  VerifyCode.click_code:
    title: 通用点击验证码
    comment: 在背景图为 @{picture_pick} 的点击验证码上，点击对应位置
    icon: captcha-click
    helpManual: ''
    inputList:
    - key: browser_obj
      title: 浏览器对象
      tip: ''
    - key: picture_pick
      title: 点击图片对象
      tip: 需要包括大的点击图片和小的指明顺序的图片
    - key: hint_position
      title: 指示顺序的图片相对大图的位置
      tip: 如果指示顺序的图片相对大图在下，则选择下，反之选择上
options:
  PictureCodeType:
  - value: '10110'
    label: 通用数英验证码1-4位
  - value: '10111'
    label: 通用数英验证码5-8位
  - value: '10211'
    label: 通用数英验证码（特殊)
  Bool:
  - value: true
    label: 是
  - value: false
    label: 否
  HintPosition:
  - value: bottom
    label: 下
  - value: top
    label: 上
