atomic:
  Window.exist:
    title: IF 窗口存在
    comment: 判断拾取窗口(@{pick})是否(@{check_type})，是就执行以下操作
    icon: check-window-exists
    helpManual: ''
    inputList:
    - key: pick
      title: 窗口拾取
      tip: 选择需要判断是否存在的窗口对象
    - key: check_type
      title: 判断方式
      tip: 选择判断方式，默认为存在
    - key: wait_time
      title: 等待时间（秒）
      tip: 等待判断结果的时间
    outputList: []
  Window.top:
    title: 置顶窗口
    comment: 置顶窗口对象(@{pick})
    icon: pin-window
    helpManual: ''
    inputList:
    - key: pick
      title: 窗口拾取
      tip: 拾取需要置顶的窗口对象
    outputList: []
  Window.close:
    title: 关闭窗口
    comment: 关闭桌面软件窗口对象(@{pick})
    icon: close-window
    helpManual: ''
    inputList:
    - key: pick
      title: 窗口拾取
      tip: 拾取需要置顶的窗口对象
    outputList: []
  Window.set_size:
    title: 调整窗口大小
    comment: 调整拾取到的窗口(@{pick})大小，通过(@{size_type:自定义})的形式将窗口宽度和高度分别设置为(@{width}) (@{height})
    icon: resize-window
    helpManual: ''
    inputList:
    - key: pick
      title: 窗口拾取
      tip: 拾取需要调整大小的桌面软件窗口
    - key: size_type
      title: 调整方式
      tip: ''
    - key: width
      title: 窗口宽度
      tip: 设置指定窗口宽度值，单位为屏幕的分辨率像素px，一般为0-9999之间的数值
    - key: height
      title: 窗口高度
      tip: 设置指定窗口高度值，单位为屏幕的分辨率像素px，一般为0-9999之间的数值
    outputList: []
options:
  WindowExistType:
  - value: exist
    label: 存在
  - value: not_exist
    label: 不存在
  WindowSizeType:
  - value: custom
    label: 自定义
  - value: max
    label: 最大化
  - value: min
    label: 最小化
