atomic:
  Encrypt.md5_encrypt:
    title: MD5加密
    comment: 对字符串(@{source_str})进行MD5加密
    icon: md5-encrypt
    helpManual: ''
    inputList:
    - key: source_str
      title: 需要加密的字符串
      tip: ''
    - key: md5_method
      title: 加密位数
      tip: ''
    - key: case_method
      title: 大小写选择
      tip: ''
    outputList:
    - key: md5_encrypted_result
      title: MD5加密结果
      tip: ''
  Encrypt.sha_encrypt:
    title: SHA加密
    comment: 对字符串(@{source_str})进行SHA加密
    icon: sha-encrypt
    helpManual: ''
    inputList:
    - key: source_str
      title: 需要加密的字符串
      tip: ''
    - key: sha_method
      title: SHA加密方法
      tip: ''
    - key: case_method
      title: 大小写选择
      tip: ''
    outputList:
    - key: sha_encrypted_result
      title: SHA加密结果
      tip: ''
  Encrypt.symmetric_encrypt:
    title: 对称加密
    comment: 对字符串(@{source_str})进行对称加密
    icon: symmetric-encrypt
    helpManual: ''
    inputList:
    - key: source_str
      title: 需要加密的字符串
      tip: ''
    - key: password
      title: 加密密钥
      tip: ''
    outputList:
    - key: symmetric_encrypted_result
      title: 对称加密结果
      tip: ''
  Encrypt.symmetric_decrypt:
    title: 对称解密
    comment: 对字符串(@{source_str})进行对称解密
    icon: symmetric-decrypt
    helpManual: ''
    inputList:
    - key: source_str
      title: 需要解密的字符串
      tip: ''
    - key: password
      title: 解密密钥
      tip: ''
    outputList:
    - key: symmetric_decrypted_result
      title: 对称解密结果
      tip: ''
  Encrypt.base64_encoding:
    title: Base64编码
    comment: 读取字符串或图片文件编码为Base64字符串，返回编码后的字符串(@{encoded_string})
    icon: base64-encode
    helpManual: ''
    inputList:
    - key: encode_type
      title: 编码类型
      tip: ''
    - key: string_data
      title: 字符串数据
      tip: ''
    - key: file_path
      title: 文件路径
      tip: ''
    outputList:
    - key: encoded_string
      title: 编码后的字符串
      tip: ''
  Encrypt.base64_decoding:
    title: Base64解码
    comment: 读取Base64字符串(@{string_data})，解码为字符串或图片文件
    icon: base64-decode
    helpManual: ''
    inputList:
    - key: decode_type
      title: 解码类型
      tip: ''
    - key: string_data
      title: Base64字符串
      tip: ''
    - key: file_path
      title: 图片保存文件夹
      tip: ''
    - key: file_name
      title: 图片文件名
      tip: ''
    - key: exist_handle_type
      title: 存在同名文件处理方式
      tip: 选择存在文件处理方式，支持覆盖原有文件、创建文件副本、取消保存操作
    outputList:
    - key: decoded_string
      title: 解码后的字符串/图片绝对路径
      tip: ''
options:
  MD5bitsType:
  - value: '32'
    label: 32位
  - value: '16'
    label: 16位
  EncryptCaseType:
  - value: lower
    label: 小写字母
  - value: upper
    label: 大写字母
  SHAType:
  - value: sha1
    label: sha1
  - value: sha224
    label: sha224
  - value: sha256
    label: sha256
  - value: sha384
    label: sha384
  - value: sha512
    label: sha512
  - value: sha3_224
    label: sha3_224
  - value: sha3_256
    label: sha3_256
  - value: sha3_384
    label: sha3_384
  - value: sha3_512
    label: sha3_512
  Base64CodeType:
  - value: string
    label: 字符串
  - value: picture
    label: 图片
  FileExistenceType:
  - value: overwrite
    label: 覆盖原有文件
  - value: rename
    label: 创建文件副本
  - value: cancel
    label: 取消保存操作
