atomic:
  Enterprise.upload_to_sharefolder:
    title: 上传文件至共享文件夹
    comment: 上传 @{file_path} 的文件，返回上传结果 @{upload_result}
    icon: ''
    helpManual: ''
    inputList:
      - key: file_path
        title: 上传文件路径
        tip: ''
    outputList:
      - key: upload_result
        title: 上传文件结果
        tip: ''
  Enterprise.download_from_sharefolder:
    title: 从共享文件夹下载文件
    comment: 下载 @{file_path} 的文件到 @{save_folder}，返回下载结果 @{download_result}
    icon: ''
    helpManual: ''
    inputList:
      - key: file_path
        title: 共享文件夹文件
        tip: ''
      - key: save_folder
        title: 文件保存路径
        tip: ''
    outputList:
      - key: download_result
        title: 下载结果
        tip: ''
  Enterprise.get_shared_variable:
    title: 获取共享变量
    comment: 获取共享变量 @{shared_variable} 给变量 @{variable_data}
    icon: get-shared-variable
    helpManual: ''
    inputList:
      - key: shared_variable
        title: 共享变量名
        tip: 选择需要的共享变量
    outputList:
      - key: variable_data
        title: 保存共享变量至
        tip: ''
options: {}

