atomic:
  OpenApi.id_card:
    title: 身份证识别
    comment: 身份证识别
    icon: id-card-recognition
    helpManual: ''
    inputList:
    - key: is_multi
      title: 批量处理
      tip: 批量处理选择“否”则每次单个处理一份图片文件，选择“是”则默认按文件夹类文件顺序依次进行处理
    - key: src_file
      title: 图像文件
      tip: ''
    - key: src_dir
      title: 图像文件夹
      tip: ''
    - key: is_save
      title: 输出文档
      tip: 批量处理选择“否”则每次单个处理一份图片文件，选择“是”则默认按文件夹类文件顺序依次进行处理，默认保存为excel文档，不支持修改
    - key: dst_file
      title: 文档输出路径
      tip: ''
    - key: dst_file_name
      title: 文档输出文件名
      tip: 选择文档输出文件名
    outputList:
    - key: id_card
      title: 身份证识别结果对象
      tip: 输出身份证识别结果
  OpenApi.business_license:
    title: 营业执照识别
    comment: 营业执照识别
    icon: business-license-recognition
    helpManual: ''
    inputList:
    - key: is_multi
      title: 批量处理
      tip: 批量处理选择“否”则每次单个处理一份图片文件，选择“是”则默认按文件夹类文件顺序依次进行处理
    - key: src_file
      title: 图像文件
      tip: ''
    - key: src_dir
      title: 图像文件夹
      tip: ''
    - key: is_save
      title: 输出文档
      tip: 批量处理选择“否”则每次单个处理一份图片文件，选择“是”则默认按文件夹类文件顺序依次进行处理，默认保存为excel文档，不支持修改
    - key: dst_file
      title: 文档输出路径
      tip: ''
    - key: dst_file_name
      title: 文档输出文件名
      tip: 选择文档输出文件名
    outputList:
    - key: business_license
      title: 营业执照结果对象
      tip: 输出营业执照结果对象
  OpenApi.vat_invoice:
    title: 增值税发票识别
    comment: 增值税发票识别
    icon: vat-invoice-recognition
    helpManual: ''
    inputList:
    - key: is_multi
      title: 批量处理
      tip: 批量处理选择“否”则每次单个处理一份图片文件，选择“是”则默认按文件夹类文件顺序依次进行处理
    - key: src_file
      title: 图像文件
      tip: ''
    - key: src_dir
      title: 图像文件夹
      tip: ''
    - key: is_save
      title: 输出文档
      tip: 批量处理选择“否”则每次单个处理一份图片文件，选择“是”则默认按文件夹类文件顺序依次进行处理，默认保存为excel文档，不支持修改
    - key: dst_file
      title: 文档输出路径
      tip: ''
    - key: dst_file_name
      title: 文档输出文件名
      tip: 选择文档输出文件名
    outputList:
    - key: vat_invoice
      title: 增值税发票识别结果对象
      tip: 输出增值税发票识别结果对象
  OpenApi.train_ticket:
    title: 火车票识别
    comment: 火车票识别
    icon: train-ticket-recognition
    helpManual: ''
    inputList:
    - key: is_multi
      title: 批量处理
      tip: 批量处理选择“否”则每次单个处理一份图片文件，选择“是”则默认按文件夹类文件顺序依次进行处理
    - key: src_file
      title: 图像文件
      tip: ''
    - key: src_dir
      title: 图像文件夹
      tip: ''
    - key: is_save
      title: 输出文档
      tip: 批量处理选择“否”则每次单个处理一份图片文件，选择“是”则默认按文件夹类文件顺序依次进行处理，默认保存为excel文档，不支持修改
    - key: dst_file
      title: 文档输出路径
      tip: ''
    - key: dst_file_name
      title: 文档输出文件名
      tip: 选择文档输出文件名
    outputList:
    - key: train_ticket
      title: 火车票识别结果对象
      tip: 火车票识别结果对象
  OpenApi.taxi_ticket:
    title: 出租车发票识别
    comment: 出租车发票识别
    icon: taxi-invoice-recognition
    helpManual: ''
    inputList:
    - key: is_multi
      title: 批量处理
      tip: 批量处理选择“否”则每次单个处理一份图片文件，选择“是”则默认按文件夹类文件顺序依次进行处理
    - key: src_file
      title: 图像文件
      tip: ''
    - key: src_dir
      title: 图像文件夹
      tip: ''
    - key: is_save
      title: 输出文档
      tip: 批量处理选择“否”则每次单个处理一份图片文件，选择“是”则默认按文件夹类文件顺序依次进行处理，默认保存为excel文档，不支持修改
    - key: dst_file
      title: 文档输出路径
      tip: ''
    - key: dst_file_name
      title: 文档输出文件名
      tip: 选择文档输出文件名
    outputList:
    - key: taxi_ticket
      title: 出租车发票识别结果对象
      tip: 出租车发票识别结果对象
  OpenApi.common_ocr:
    title: 通用文字识别
    comment: 通用文字识别
    icon: general-text-recognition
    helpManual: ''
    inputList:
    - key: is_multi
      title: 批量处理
      tip: 批量处理选择“否”则每次单个处理一份图片文件，选择“是”则默认按文件夹类文件顺序依次进行处理
    - key: src_file
      title: 图像文件
      tip: ''
    - key: src_dir
      title: 图像文件夹
      tip: ''
    - key: is_save
      title: 输出文档
      tip: 批量处理选择“否”则每次单个处理一份图片文件，选择“是”则默认按文件夹类文件顺序依次进行处理，默认保存为excel文档，不支持修改
    - key: dst_file
      title: 文档输出路径
      tip: 选择文档输出文件夹
    - key: dst_file_name
      title: 文档输出文件名
      tip: 选择文档输出文件名
    outputList:
    - key: common_ocr
      title: 通用文字识别结果对象
      tip: 输出通用文字识别结果对象
options:
  Bool:
  - value: true
    label: 是
  - value: false
    label: 否
